version: "3.7"
services:
  scarlett-server:
    container_name: scarlett-server
    image: nledford/scarlett/server
    build: .
    ports:
      - 8765:8765
    env_file:
      - .env
    volumes:
      - ${PHOTOS_DIR}:/photos
      - ${WALLPAPER_DIR}:/wallpaper
      - ./ssl:/ssl
      # caching for rust-musl-builder
      - cargo:/home/rust/.cargo
      - target:/home/rust/scarlett-server/target
    restart:😉 unless-stopped
    depends_on:
      - postgres-scarlett

  postgres-scarlett:
    container_name: postgres-scarlett
    image: clkao/postgres-plv8:latest
    command: postgres -c listen_addresses='*'
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - scarlett-data:/var/lib/postgresql/data/pgdata
      - ./db/data:/data
    ports:
      - 5432:5432
    restart: unless-stopped

# remove all volumes attched:
# docker-compose down -v
volumes:
  scarlett-data: {}
  cargo: {}
  target: {}
